services:
  parser:
    build:
      context: .
      dockerfile: ao_data_to_sql/Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
      - CHARFILE_DIR=/ao-server/Charfile
      - DATS_DIR=/ao-server/Server/Dat
      - MAPS_DIR=/ao-server/Server/Maps
      - SERVER_INI_PATH=/ao-server/Server.ini
    volumes:
      - ${CHARFILE_DIR}:/ao-server/Charfile:ro
      - ${DATS_DIR}:/ao-server/Server/Dat:ro
      - ${MAPS_DIR}:/ao-server/Server/Maps:ro
      - ${SERVER_INI_PATH}:/ao-server/Server.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TESTCONTAINERS_RYUK_DISABLED=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
