//! DAT file import orchestration.
//!
//! Provides named import functions for each supported DAT file type.
//! All share a private generic helper that handles existence checks,
//! modification checks, timing, and logging. The public wrappers are
//! generated by the `dat_importer!` macro — one invocation per file type.

use std::path::Path;
use std::time::{Instant, SystemTime};

use anyhow::{Context, Result};
use sqlx::PgPool;
use tracing::{info, warn};

use crate::db::{
    insert_balance, insert_blacksmith_armors, insert_blacksmith_weapons,
    insert_carpenter_objects, insert_faction_armors, insert_npcs,
    insert_objects, insert_spells, prepare_balance_data,
    prepare_blacksmith_armor_data, prepare_blacksmith_weapon_data,
    prepare_carpenter_object_data, prepare_faction_armor_data,
    prepare_npc_data, prepare_object_data, prepare_spell_data,
};
use crate::execution_tracking::was_modified_since;
use crate::parsers::dat::{
    balance::parse_balance_file,
    blacksmith_armors::parse_blacksmith_armors_file,
    blacksmith_weapons::parse_blacksmith_weapons_file,
    carpenter::parse_carpenter_file,
    faction_armors::parse_faction_armors_file, npcs::parse_npcs_file,
    objects::parse_objects_file, spells::parse_spells_file,
};

/// Orchestrates a single-file DAT import.
///
/// Returns early if the file is missing or unmodified since `last_exec`.
/// `import_fn` receives the resolved path and must return
/// `(parsed, inserted, errors)`.
async fn import_dat_file<F, Fut>(
    dats_dir: &Path,
    filename: &str,
    label: &str,
    last_exec: Option<SystemTime>,
    import_fn: F,
) -> Result<()>
where
    F: FnOnce(&Path) -> Fut,
    Fut: core::future::Future<Output = Result<(usize, usize, usize)>>,
{
    let path = dats_dir.join(filename);

    if !path.exists() {
        warn!("{} no encontrado en {}", filename, path.display());
        return Ok(());
    }

    if !was_modified_since(&path, last_exec) {
        info!("{}: no modificado desde la ultima ejecucion", label);
        return Ok(());
    }

    let start = Instant::now();
    let (parsed, inserted, errors) = import_fn(&path).await?;
    let elapsed = start.elapsed().as_secs_f64();

    info!(
        "{}: {} parseados, {} insertados, {} errores, {:.3}s",
        label, parsed, inserted, errors, elapsed
    );

    Ok(())
}

/// Generates a public async import function for a single DAT file type.
///
/// Each expansion produces a function with the standard signature and delegates
/// to the private `import_dat_file` helper for existence checks, modification
/// checks, timing, and logging.
macro_rules! dat_importer {
    (
        $fn_name:ident,
        $filename:literal,
        $label:literal,
        $parse_fn:path,
        $prepare_fn:path,
        $insert_fn:path
    ) => {
        pub async fn $fn_name(
            pool: &PgPool,
            dats_dir: &Path,
            last_exec: Option<SystemTime>,
            strip_comments: bool,
            batch_size: usize,
        ) -> Result<()> {
            import_dat_file(
                dats_dir,
                $filename,
                $label,
                last_exec,
                |file_path| {
                    let pool_cloned = pool.clone();
                    let path_owned = file_path.to_owned();
                    async move {
                        let parsed = $parse_fn(&path_owned, strip_comments)
                            .context(concat!("Error parseando ", $filename))?;
                        let count = parsed.len();
                        let (inserted, errors) = $insert_fn(
                            &pool_cloned,
                            &$prepare_fn(parsed),
                            batch_size,
                        )
                        .await;
                        Ok((count, inserted, errors))
                    }
                },
            )
            .await
        }
    };
}

dat_importer!(
    import_npcs,
    "NPCs.dat",
    "NPCs",
    parse_npcs_file,
    prepare_npc_data,
    insert_npcs
);
dat_importer!(
    import_objects,
    "Obj.dat",
    "Objetos",
    parse_objects_file,
    prepare_object_data,
    insert_objects
);
dat_importer!(
    import_spells,
    "Hechizos.dat",
    "Hechizos",
    parse_spells_file,
    prepare_spell_data,
    insert_spells
);
dat_importer!(
    import_carpenter_objects,
    "ObjCarpintero.dat",
    "ObjCarpintero",
    parse_carpenter_file,
    prepare_carpenter_object_data,
    insert_carpenter_objects
);
dat_importer!(
    import_blacksmith_armors,
    "ArmadurasHerrero.dat",
    "ArmadurasHerrero",
    parse_blacksmith_armors_file,
    prepare_blacksmith_armor_data,
    insert_blacksmith_armors
);
dat_importer!(
    import_blacksmith_weapons,
    "ArmasHerrero.dat",
    "ArmasHerrero",
    parse_blacksmith_weapons_file,
    prepare_blacksmith_weapon_data,
    insert_blacksmith_weapons
);
dat_importer!(
    import_faction_armors,
    "ArmadurasFaccionarias.dat",
    "ArmadurasFaccionarias",
    parse_faction_armors_file,
    prepare_faction_armor_data,
    insert_faction_armors
);
dat_importer!(
    import_balance,
    "Balance.dat",
    "Balance",
    parse_balance_file,
    prepare_balance_data,
    insert_balance
);
